<?php

namespace App\Repository;

use App\Entity\Photo;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function listEtablissement_($_iPage, $_sSort, $_iSize = 3) {
        $qb = $this->createQueryBuilder('e')
            ->andWhere('e.id > 0')
            ->orderBy('e.'.$_sSort, 'ASC')
            ->setMaxResults($_iSize)
            ->setFirstResult($_iPage);
       return $qb;
    }
    
    public function listEtablissement($sType = '', $_sSort = 'id', $_iSize = 12) {
        $qb = $this->createQueryBuilder('e')
            ->where('e.id > 0')
            ->setMaxResults($_iSize)
            ->orderBy('e.'.$_sSort, 'ASC');
        if (!empty($sType)) {
            $qb->andWhere('e.type = :stype')->setParameter('stype', $sType);
        }
       return $qb;
    }
    
    public function searchEtablissement($aSearch, $_sSort = 'id') {
        $qb = $this->createQueryBuilder('e');
            if (!empty($aSearch['nom'])) {
                $qb->andWhere("e.nom like '%".$aSearch['nom']."%'");
            }
            if (!empty($aSearch['lieu'])) {
                $qb->andWhere("e.adresse like '%".$aSearch['lieu']."%'");
            }
            if (!empty($aSearch['budget'])) {
                $qb->andWhere("e.prix <= ".$aSearch['budget']);
            }
            if (!empty($aSearch['type'])) {
                $qb->andWhere("e.type like :stype")->setParameter('stype', $aSearch['type']);
            }
            $qb->orderBy('e.'.$_sSort, 'ASC');
        $qb->leftJoin(Photo::class, 'photo', 'with', 'photo.idEtablissement = e.id');
       return $qb;
    }
}
